version: '3'
services:
  db:
    image: mysql:8.0.26
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpassword
      - MYSQL_USER=journaluser
      - MYSQL_PASSWORD=journalpassword
      - MYSQL_DATABASE=journal_db

  journal-backend:
    image: journal-backend
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/journal_db
      SPRING_DATASOURCE_USERNAME: journaluser
      SPRING_DATASOURCE_PASSWORD: journalpassword
    build:
      context: "."
      dockerfile: "Dockerfile"